'use client';

import { motion } from 'framer-motion';
import Link from 'next/link';
import { useTranslations } from 'next-intl';

import { getTopicDisplayName } from '@/lib/channels/ai-name-generator.client';
import { getThemeStyle } from '@/lib/channels/theme-styles';
import type { ChannelSummary } from '@/lib/channels/types';

interface PlanetCardProps {
  channel: ChannelSummary;
  /** Locale for routing */
  locale: string;
}

/**
 * PlanetCard - Visual representation of an auto-generated channel as a "planet" in the user's universe
 *
 * Features:
 * - Gradient background based on topic
 * - Soft glow effect on hover
 * - AI-generated display name (with theme fallback)
 * - Topic chip for classification
 * - Stats: vibelog count + last activity
 */
export function PlanetCard({ channel, locale }: PlanetCardProps) {
  const t = useTranslations();
  const themeStyle = getThemeStyle(channel.primary_topic);
  const Icon = themeStyle.icon;

  // Display name: prefer AI name, fallback to theme display name
  const displayName =
    channel.ai_display_name || getTopicDisplayName(channel.primary_topic || 'other');

  // Theme name for the chip
  const themeName = channel.primary_topic
    ? t(`themes.${channel.primary_topic}`)
    : t('themes.other');

  return (
    <Link href={`/${locale}/c/${channel.handle}`} className="group block">
      <motion.div
        className={`relative overflow-hidden rounded-2xl bg-gradient-to-br p-5 ${themeStyle.gradient} cursor-pointer transition-all duration-300 ease-out`}
        whileHover={{
          scale: 1.02,
          boxShadow: `0 8px 32px ${themeStyle.glowColor}, 0 4px 16px ${themeStyle.glowColor}`,
        }}
        whileTap={{ scale: 0.98 }}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.3 }}
      >
        {/* Glow overlay on hover */}
        <div
          className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-300 group-hover:opacity-20"
          style={{
            background: `radial-gradient(circle at 50% 0%, white 0%, transparent 70%)`,
          }}
        />

        {/* Icon */}
        <div className="mb-3">
          <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-white/20 backdrop-blur-sm">
            <Icon className="h-6 w-6 text-white" />
          </div>
        </div>

        {/* Display Name (AI name or theme fallback) */}
        <h3 className="mb-1 line-clamp-1 text-lg font-semibold text-white">{displayName}</h3>

        {/* Theme Chip */}
        <div className="mb-3">
          <span className="inline-flex items-center rounded-full bg-white/20 px-2 py-0.5 text-xs font-medium text-white/90">
            {themeName}
          </span>
        </div>

        {/* Stats */}
        <div className="flex items-center gap-3 text-sm text-white/80">
          <span>
            {channel.vibelog_count} {t('universe.vibelogs')}
          </span>
          {channel.auto_generated && (
            <span className="flex items-center gap-1">
              <span className="h-1.5 w-1.5 rounded-full bg-white/60" />
              {t('universe.autoGenerated')}
            </span>
          )}
        </div>

        {/* Subtle pulse animation for auto-generated channels */}
        {channel.auto_generated && (
          <motion.div
            className="absolute right-3 top-3 h-2 w-2 rounded-full bg-white/60"
            animate={{
              scale: [1, 1.5, 1],
              opacity: [0.6, 0.3, 0.6],
            }}
            transition={{
              duration: 2,
              repeat: Infinity,
              ease: 'easeInOut',
            }}
          />
        )}
      </motion.div>
    </Link>
  );
}

/**
 * PlanetCardSkeleton - Loading state for PlanetCard
 */
export function PlanetCardSkeleton() {
  return (
    <div className="relative animate-pulse overflow-hidden rounded-2xl bg-gradient-to-br from-gray-200 to-gray-300 p-5 dark:from-gray-700 dark:to-gray-800">
      <div className="mb-3">
        <div className="h-12 w-12 rounded-xl bg-gray-300 dark:bg-gray-600" />
      </div>
      <div className="mb-2 h-5 w-32 rounded bg-gray-300 dark:bg-gray-600" />
      <div className="mb-3 h-4 w-20 rounded-full bg-gray-300 dark:bg-gray-600" />
      <div className="h-4 w-24 rounded bg-gray-300 dark:bg-gray-600" />
    </div>
  );
}
